title: Matheus Costa - UX/UI Designer e Desenvolvedor Front-end em São José do Rio Preto/SP
description: Profissional especializado em criação de sites em São José do Rio Preto/SP

baseurl: ""
url: "https://matheuscostadesign.github.io"

twitter_username: jekyllrb
github_username: jekyll
email: matheuscostadosantos@hotmail.com

# Build settings
# theme: minima
#permalink: /blog/:categories/:title/
permalink: /blog/:title/

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
