title: Matheus Costa - UX/UI Designer e Desenvolvedor Front-end em São José do Rio Preto/SP
description: Profissional especializado em criação de sites em São José do Rio Preto/SP

baseurl: ""
url: "https://matheuscostadesign.github.io"

# Author Settings
author:
  name: Matheus Costa
  img: "/assets/matheus.jpg"
  blog: https://matheuscostadesign.github.io
  email: matheuscostadosantos@hotmail.com
  twitter: matheuscosta.design
  github: matheuscostadesign
  bio: Profissional especializado em criação de sites em São José do Rio Preto/SPdo autor

# Build settings
#permalink: /blog/:categories/:title/
permalink: /blog/:title/

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-feed
