source "https://rubygems.org"

# Use GitHub Pages.
gem "github-pages", group: :jekyll_plugins

# Plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Required by GitHub pages to avoid alerts
gem "activesupport", ">= 6.0.3.1"


gem "webrick", "~> 1.7"
